### ISSUE TITLE
ドメインのコンストラクタに前提条件を追加する

### ISSUE THREAD

**Issue by syobochim** [syobochim/kajipoi#1]
うらがみさんがやってた。

永続層のデータ不正を防ぐためかな…？

こんな感じでNullチェックやvalueの長さチェックなどする。

```
Objects.requireNonNull(value);
```

**Comment by backpaper0** [comment]
|･`ω･)ﾁﾗｯ

**Comment by backpaper0** [comment]
データ不正を防ぐためで合ってるよ！
あと、Javaのオブジェクトとして見たときにも不正でないことを保証したい。
コンストラクタでチェックしてとくと不正なインスタンスは作れないので安心～

**Comment by syobochim** [comment]
はっ！ありがとうございます！学び多いー！

**Comment by syobochim** [comment]
コミットコメントとissueの内容がずれてる。。。
valueOfとかのはなしばっかり〜

**Comment by backpaper0** [comment]
わろたwww

**Comment by syobochim** [comment]
てへ！
